// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="home_alarm_home_alarm,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.226500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=142,HLS_VERSION=2020_2}" *)

module home_alarm (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        switches,
        sg_data,
        sg_data_ap_vld,
        sg_enable,
        sg_enable_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] switches;
output  [7:0] sg_data;
output   sg_data_ap_vld;
output  [3:0] sg_enable;
output   sg_enable_ap_vld;

reg sg_data_ap_vld;
reg sg_enable_ap_vld;

wire   [0:0] icmp_ln870_fu_122_p2;
wire   [3:0] switch_code_fu_112_p4;
wire   [2:0] window_sensors_V_fu_86_p1;
wire   [1:0] motion_sensors_V_fu_94_p4;
wire   [0:0] trunc_ln5_fu_90_p1;
wire   [0:0] tmp_1_fu_146_p3;
wire   [0:0] p_Result_2_fu_160_p3;
wire   [0:0] icmp_ln874_1_fu_134_p2;
wire   [0:0] icmp_ln874_fu_128_p2;
wire   [0:0] xor_ln874_fu_184_p2;
wire   [0:0] and_ln874_fu_190_p2;
wire   [0:0] p_Result_s_fu_140_p2;
wire   [0:0] or_ln819_fu_204_p2;
wire   [7:0] select_ln874_fu_196_p3;
wire   [0:0] p_Result_1_fu_154_p2;
wire   [0:0] xor_ln874_1_fu_218_p2;
wire   [0:0] and_ln819_fu_224_p2;
wire   [0:0] and_ln819_1_fu_230_p2;
wire   [7:0] select_ln20_fu_168_p3;
wire   [7:0] select_ln819_fu_210_p3;
wire   [1:0] select_ln874_1_fu_244_p3;
wire   [1:0] select_ln20_1_fu_176_p3;
wire   [1:0] select_ln819_2_fu_252_p3;
wire   [1:0] select_ln819_3_fu_260_p3;
wire   [0:0] tmp_fu_104_p3;
wire   [0:0] p_Result_4_fu_278_p3;
wire   [7:0] select_ln819_1_fu_236_p3;
wire  signed [2:0] sext_ln819_fu_268_p1;
wire   [0:0] p_Result_3_fu_272_p2;
wire   [0:0] tmp79_fu_302_p2;
wire   [0:0] and_ln874_1_fu_314_p2;
wire   [0:0] and_ln874_2_fu_320_p2;
wire   [0:0] and_ln874_3_fu_334_p2;
wire   [0:0] and_ln874_4_fu_340_p2;
wire   [7:0] select_ln874_2_fu_326_p3;
wire   [0:0] sel_tmp39_fu_308_p2;
wire   [7:0] select_ln29_fu_286_p3;
wire   [7:0] select_ln874_3_fu_346_p3;
wire   [2:0] select_ln874_4_fu_363_p3;
wire   [2:0] select_ln29_1_fu_294_p3;
wire   [2:0] select_ln874_5_fu_371_p3;
wire   [2:0] sg_enable_new_1_fu_379_p3;
wire    ap_ce_reg;

always @ (*) begin
    if (((ap_start == 1'b1) & (icmp_ln870_fu_122_p2 == 1'd1))) begin
        sg_data_ap_vld = 1'b1;
    end else begin
        sg_data_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (icmp_ln870_fu_122_p2 == 1'd1))) begin
        sg_enable_ap_vld = 1'b1;
    end else begin
        sg_enable_ap_vld = 1'b0;
    end
end

assign and_ln819_1_fu_230_p2 = (p_Result_s_fu_140_p2 & and_ln819_fu_224_p2);

assign and_ln819_fu_224_p2 = (xor_ln874_1_fu_218_p2 & p_Result_1_fu_154_p2);

assign and_ln874_1_fu_314_p2 = (icmp_ln874_fu_128_p2 & icmp_ln874_1_fu_134_p2);

assign and_ln874_2_fu_320_p2 = (icmp_ln870_fu_122_p2 & and_ln874_1_fu_314_p2);

assign and_ln874_3_fu_334_p2 = (xor_ln874_1_fu_218_p2 & icmp_ln874_1_fu_134_p2);

assign and_ln874_4_fu_340_p2 = (icmp_ln870_fu_122_p2 & and_ln874_3_fu_334_p2);

assign and_ln874_fu_190_p2 = (xor_ln874_fu_184_p2 & icmp_ln874_fu_128_p2);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign icmp_ln870_fu_122_p2 = ((switch_code_fu_112_p4 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln874_1_fu_134_p2 = ((motion_sensors_V_fu_94_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln874_fu_128_p2 = ((window_sensors_V_fu_86_p1 == 3'd0) ? 1'b1 : 1'b0);

assign motion_sensors_V_fu_94_p4 = {{switches[7:6]}};

assign or_ln819_fu_204_p2 = (p_Result_s_fu_140_p2 | icmp_ln874_fu_128_p2);

assign p_Result_1_fu_154_p2 = (tmp_1_fu_146_p3 ^ 1'd1);

assign p_Result_2_fu_160_p3 = switches[32'd2];

assign p_Result_3_fu_272_p2 = (tmp_fu_104_p3 ^ 1'd1);

assign p_Result_4_fu_278_p3 = switches[32'd7];

assign p_Result_s_fu_140_p2 = (trunc_ln5_fu_90_p1 ^ 1'd1);

assign sel_tmp39_fu_308_p2 = (tmp79_fu_302_p2 & icmp_ln870_fu_122_p2);

assign select_ln20_1_fu_176_p3 = ((p_Result_2_fu_160_p3[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign select_ln20_fu_168_p3 = ((p_Result_2_fu_160_p3[0:0] == 1'b1) ? 8'd176 : 8'd146);

assign select_ln29_1_fu_294_p3 = ((p_Result_4_fu_278_p3[0:0] == 1'b1) ? 3'd5 : sext_ln819_fu_268_p1);

assign select_ln29_fu_286_p3 = ((p_Result_4_fu_278_p3[0:0] == 1'b1) ? 8'd164 : select_ln819_1_fu_236_p3);

assign select_ln819_1_fu_236_p3 = ((and_ln819_1_fu_230_p2[0:0] == 1'b1) ? select_ln20_fu_168_p3 : select_ln819_fu_210_p3);

assign select_ln819_2_fu_252_p3 = ((or_ln819_fu_204_p2[0:0] == 1'b1) ? select_ln874_1_fu_244_p3 : 2'd2);

assign select_ln819_3_fu_260_p3 = ((and_ln819_1_fu_230_p2[0:0] == 1'b1) ? select_ln20_1_fu_176_p3 : select_ln819_2_fu_252_p3);

assign select_ln819_fu_210_p3 = ((or_ln819_fu_204_p2[0:0] == 1'b1) ? select_ln874_fu_196_p3 : 8'd249);

assign select_ln874_1_fu_244_p3 = ((and_ln874_fu_190_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign select_ln874_2_fu_326_p3 = ((and_ln874_2_fu_320_p2[0:0] == 1'b1) ? 8'd192 : 8'd249);

assign select_ln874_3_fu_346_p3 = ((and_ln874_4_fu_340_p2[0:0] == 1'b1) ? select_ln819_1_fu_236_p3 : select_ln874_2_fu_326_p3);

assign select_ln874_4_fu_363_p3 = ((and_ln874_2_fu_320_p2[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign select_ln874_5_fu_371_p3 = ((and_ln874_4_fu_340_p2[0:0] == 1'b1) ? sext_ln819_fu_268_p1 : select_ln874_4_fu_363_p3);

assign select_ln874_fu_196_p3 = ((and_ln874_fu_190_p2[0:0] == 1'b1) ? 8'd146 : 8'd164);

assign sext_ln819_fu_268_p1 = $signed(select_ln819_3_fu_260_p3);

assign sg_data = ((sel_tmp39_fu_308_p2[0:0] == 1'b1) ? select_ln29_fu_286_p3 : select_ln874_3_fu_346_p3);

assign sg_enable = $signed(sg_enable_new_1_fu_379_p3);

assign sg_enable_new_1_fu_379_p3 = ((sel_tmp39_fu_308_p2[0:0] == 1'b1) ? select_ln29_1_fu_294_p3 : select_ln874_5_fu_371_p3);

assign switch_code_fu_112_p4 = {{switches[15:12]}};

assign tmp79_fu_302_p2 = (xor_ln874_fu_184_p2 & p_Result_3_fu_272_p2);

assign tmp_1_fu_146_p3 = switches[32'd1];

assign tmp_fu_104_p3 = switches[32'd6];

assign trunc_ln5_fu_90_p1 = switches[0:0];

assign window_sensors_V_fu_86_p1 = switches[2:0];

assign xor_ln874_1_fu_218_p2 = (icmp_ln874_fu_128_p2 ^ 1'd1);

assign xor_ln874_fu_184_p2 = (icmp_ln874_1_fu_134_p2 ^ 1'd1);

endmodule //home_alarm
